# Generated by Django 4.0.3 on 2023-09-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0008_rename_code_product_hd_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
