# Generated by Django 4.0.3 on 2023-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0009_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(choices=[('1', 'HP'), ('2', 'DELL')], default=1, max_length=25),
        ),
    ]
