# Generated by Django 4.0.3 on 2023-09-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0012_alter_product_model_alter_product_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Assigned'), ('2', 'Unassigned')], default=1, max_length=2),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Invoice_Item',
        ),
    ]
