# Generated by Django 4.0.3 on 2023-09-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0013_remove_invoice_item_invoice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Employee',
        ),
    ]
